name: Docker Image

on: 
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/multitheftauto/mtasa-blue-gcc:latest
        provenance: mode=max
        cache-from: type=gha
        cache-to: type=gha, mode=max
