name: Docker Image

on: 
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx-
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ghcr.io/multitheftauto/mtasa-blue-gcc:latest
          ghcr.io/multitheftauto/mtasa-blue-gcc:noble
          ghcr.io/multitheftauto/mtasa-blue-gcc:15-noble
        cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
        cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max
    - name: Move cache
      run: |
        rm -rf ${{ runner.temp }}/.buildx-cache
        mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
